### ISSUE TITLE
Object #<Canvas> has no method 'addEventListener'

### ISSUE THREAD

**Issue by tk120404** [wdamien/node-easel#3]
Getting following error message on running the server.js

TypeError: Object #<Canvas> has no method 'addEventListener'
    at p.enableDOMEvents (/home/game/node_modules/node-easel/src/easeljs/display/Stage.js:427:9)
    at p.initialize (/home/game/node_modules/node-easel/src/easeljs/display/Stage.js:259:8)
    at Stage (/home/game/node_modules/node-easel/src/easeljs/display/Stage.js:58:8)
    at Object.p.init (/home/game/captcha.js:47:14)
    at Object.Captcha (/home/game/captcha.js:33:14)
    at /home/game/server.js:22:13
    at callbacks (/home/game/node_modules/express/lib/router/index.js:161:37)
    at param (/home/game/node_modules/express/lib/router/index.js:135:11)
    at pass (/home/game/node_modules/express/lib/router/index.js:142:5)
    at Router._dispatch (/home/game/node_modules/express/lib/router/index.js:170:5)

**Comment by wdamien** [comment]
I can''t reproduce this on my dev server.  Can you provide some more information on your setup?
What OS are your running? 
Also whats your node version?  Thanks!

**Comment by tk120404** [comment]
I tried it in Ubuntu 12.10 64bit and node v0.8.21

**Comment by tk120404** [comment]
it works well with 0.10.0 and not with 0.11.2

**Comment by namelivia** [comment]
Im having the same issue here, I'm using node v0.10.24

**Comment by bingomanatee** [comment]
/Users/dave/Documents/repos/famousScrollTest/node_modules/node-easel/src/easeljs/display/Stage.js:525
                o.t.addEventListener(n, o.f, false);
                    ^
TypeError: Object #<Canvas> has no method 'addEventListener'
    at p.enableDOMEvents (/Users/dave/Documents/repos/famousScrollTest/node_modules/node-easel/src/easeljs/display/Stage.js:525:9)
    at p.initialize (/Users/dave/Documents/repos/famousScrollTest/node_modules/node-easel/src/easeljs/display/Stage.js:338:8)
    at Stage (/Users/dave/Documents/repos/famousScrollTest/node_modules/node-easel/src/easeljs/display/Stage.js:63:8)
    at /Users/dave/Documents/repos/famousScrollTest/tests/scroll_test.js:22:21
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)
...

https://gist.github.com/bingomanatee/11353013
